### ISSUE TITLE
как запустьтьит????

### ISSUE THREAD

**Issue by ghost** [C6OI/C6OT#1]
очин хоцитца разабратьса но нимагу панять как ето запустит??? сказите пзалуста я навицок в плагламиловании

**Comment by C6OI** [comment]
Я сам не разобрался!!!!

**Comment by s809** [comment]
почему!!!!!!!!!!!!!!

**Comment by C6OI** [comment]
> почему!!!!!!!!!!!!!!

Потому что!!!!!!!!!!!!!

**Comment by ghost** [comment]
я разобрался!!!
